### ISSUE TITLE
boardswarm: Too generic error message when jwks auth file is missing

### ISSUE THREAD

**Issue by andrzejtp** [boardswarm/boardswarm#22]
While running the server if jwks auth file is missing the received message is:

```
Error: No such file or directory (os error 2)
```

which is cryptic. Information about _which_ file or directory is missing would be so helpful, otherwise the user is left guessing what's happening.

**Comment by obbardc** [comment]
Also there are small spelling issues e.g `Error: Token file doesn't look like a JTW token (too small)`

**Comment by andrzejtp** [comment]
Solved with https://github.com/obbardc/boardswarm/commit/70b4ad486632af7a89c509421c930338a255448f
