### ISSUE TITLE
cli: Add argument to remove instance's configuration

### ISSUE THREAD

**Issue by obbardc** [boardswarm/boardswarm#28]
Add a command to remove an instance from local config.

Bonus points to be able to remove it and re-add it in the same command.

**Comment by andrzejtp** [comment]
@obbardc this seems addressed with https://github.com/boardswarm/boardswarm/pull/40

No bonus points, though.

**Comment by sjoerdsimons** [comment]
I wouldn't think the -readd in the same command would make sense anyway? that just sounds like reconfiguration which `auth modify` addresses
