### ISSUE TITLE
cli: actuators, consoles and volumes should be identifiable with their names, too

### ISSUE THREAD

**Issue by andrzejtp** [boardswarm/boardswarm#59]
At this moment only devices can be identified with either their id or their name, e.g.:

```bash
$ boardswarm-cli device 2 properties
"boardswarm.name" => "rockpi4"
$ boardswarm-cli device rockpi4 properties
"boardswarm.name" => "rockpi4"
```

It should be possible to identify this way actuators, consoles and volumes.

**Comment by sjoerdsimons** [comment]
Yes currently this just works for devices; The one important think to note is that the *id* is the primary key for everything, the name does not have to be unique. For devices you'd expect the name to be unique currently as that is configured by a human and humans can deal with naming schemes..

For everything else the names are often generated by the provider in boardswarm; For example for serial consoles the name is simply the device name, so if you have multiple instances in your swarm then you'd likely have mutliple ttyS0 or ttyUSB0 devices.. As a silly example on my setup atm i have:
```
Consoles: 
1 ttyUSB0 on pipertis
2 ttyUSB3 on pipertis
3 ttyUSB4 on pipertis
4 ttyS0 on pipertis
5 ttyS2 on pipertis
6 ttyS3 on pipertis
7 ttyS0 on mox-table
8 ttyS1 on pipertis
9 ttyUSB1 on pipertis
10 ttyS0
11 ttyUSB2 on pipertis
12 ttyS1
13 ttyS2
14 ttyS3
15 ttyUSB5 on pipertis
16 ttyS1 on mox-table
17 ttyS2 on mox-table
18 ttyS3 on mox-table
19 ttyMV0 on mox-table
20 ttyUSB0 on mox-table
```
That said, as a human having to do `list consoles` first to figure out the id is annoying; So i'd be in favour of extending this.. A few different options come to mind:
- Always error out of there are multiple matches (giving a list of matches and their ids)
- Only match on the local name and force people to e.g. do `ttyUSB@mox-table` to specify  a on a remote boardswarm
- Similar to the above but accept without @xxx if it's a unique name 

Note that while there isn't even a strict guarantee that a name is unique on a single instance, practically that will always be the case. So the cli should regardless of the syntax be able to cope and error on multiple matches even in in practise there shouldn't often be ambiguity within a single instance

**Comment by andrzejtp** [comment]
https://github.com/boardswarm/boardswarm/pull/64
